BaseUrl= "http://iamShantanu101.github.io/"
LanguageCode= "en-US"
Title= "Shantanu Deshpande"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "Docker,Machine Learning,Linux"
  cover = "images/user.jpg"
  author = "Shantanu"
  authorlocation = "Mumbai,India"
  authorwebsite = "http://iamShantanu101.github.io/blog"
  bio= "Docker,Machine Learning,Linux"
  logo = "images/theflash.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "iamShantanu101"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
